"""Interfaces separating workflow policy from infrastructure."""

from datetime import datetime
from typing import Protocol

from .models import ActiveTask, AgentDecision, AgentInput, Employee, SessionState, Task


class EmployeeRepository(Protocol):
    async def bind_verified_identity(self, slack_user_id: str, email: str) -> Employee | None: ...

    async def get_employee_by_slack(self, slack_user_id: str) -> Employee | None: ...

    async def get_session(self, employee_id: str) -> SessionState: ...

    async def save_session(self, state: SessionState) -> None: ...

    async def get_next_task(self, employee_id: str) -> Task | None: ...

    async def mark_task_sent(self, employee_id: str, task: Task, sent_at: datetime) -> None: ...

    async def complete_task(self, employee_id: str, task_id: str) -> None: ...

    async def list_active_tasks(self) -> list[ActiveTask]: ...

    async def record_sla_event(self, employee_id: str, task_id: str, event: str) -> None: ...


class KnowledgeBase(Protocol):
    async def search(self, query: str) -> tuple[str, list[str]]: ...


class ConversationAgent(Protocol):
    async def respond(self, payload: AgentInput) -> AgentDecision: ...


class Notifier(Protocol):
    async def notify_employee(self, employee: Employee, text: str) -> None: ...

    async def notify_owner(self, employee: Employee, text: str) -> None: ...
